# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-26 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('download_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downloadfile',
            old_name='filedescription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='downloadfile',
            old_name='filename',
            new_name='name',
        ),
    ]
