# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-13 03:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=256)),
                ('sample', models.CharField(max_length=256)),
                ('fpkm', models.FloatField()),
            ],
            options={
                'verbose_name': 'ExpDB',
                'verbose_name_plural': 'ExpDB',
            },
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geneid', models.CharField(max_length=256)),
                ('coordinate', models.CharField(max_length=256)),
                ('strand', models.CharField(max_length=1)),
                ('best_ara', models.CharField(max_length=1000)),
                ('function_des', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='GO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession', models.CharField(max_length=256)),
                ('namespace', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genewiki_app.Gene')),
            ],
            options={
                'verbose_name': 'GO',
                'verbose_name_plural': 'GO',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('title', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='expdb',
            name='gene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genewiki_app.Gene'),
        ),
    ]
