# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-26 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genewiki_app', '0002_project_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gene',
            name='id',
        ),
        migrations.AlterField(
            model_name='gene',
            name='geneid',
            field=models.CharField(max_length=256, primary_key=True, serialize=False),
        ),
    ]
